### ISSUE TITLE
Compatibility with Matomo 4.5

### ISSUE THREAD

**Issue by HerbstO** [MichaelHeerklotz/plugin-GroupPermissions#4] opened 2021-10-27 04:59 UTC
Hello,

we have found an issue when using the plugin in Matomo 4.5. The "Manage group permissions" page glances continuously and cannot be used. Currently we can only change group permissions directly through the database. Is there a workaround for this? We checked this in 3 different Browsers. The File "plugin.json" has been changed according to your "howto".

Regards and thanks for the work so far
O. Herbst

**Comment by answeb** [comment] 2021-11-09 09:04
Hi,
Just installed the plugin following the docs, and I have the same issue.
I don't even know where to look for as the page goes crazy when loading.
I hope it will be fixed soon !
I will try to fork the plugin and fix it when I can

**Comment by MichaelRoosz** [comment] 2022-04-09 17:26
Hello @HerbstO  and @answeb does this issue still exist?
I tried to reproduce it today with Matomo 4.8.0 but so far it seems to be working fine.

**Comment by HerbstO** [comment] 2022-04-11 06:18
Hello, the issue still exists, we would like to use it under version 4.5 but when calling the plugin the "Right" page is loaded in continuous loop. The "Right" page can not be used. Our workaround is that we do the desired change in the database directly.

**Comment by MichaelRoosz** [comment] 2022-04-11 12:10
Hello @HerbstO,
thank you for your feedback. 
The issue should be fixed in v4.0.2.
At the moment I cannot push released to the Matomo marketplace, but the Matomo team is working on it.
Meanwhile you may download v4.0.2 directly here on github.

Greetings,
Michael

**Comment by HerbstO** [comment] 2022-04-11 12:12
Hello,
thats good News, i will wait fort he new Version.

Thanks for your Work.

Best Regards

Viele Grüße und „Bleiben Sie Gesund“
Ortwin Herbst
BAS3

Von: MichaelRoosz ***@***.***>
Gesendet: Montag, 11. April 2022 14:11
An: MichaelRoosz/plugin-GroupPermissions ***@***.***>
Cc: Herbst Ortwin ***@***.***>; Mention ***@***.***>
Betreff: Re: [MichaelRoosz/plugin-GroupPermissions] Compatibility with Matomo 4.5 (Issue #4)


Hello @HerbstO<https://github.com/HerbstO>,
thank you for your feedback.
The issue should be fixed in v4.0.2.
At the moment I cannot push released to the Matomo marketplace, but the Matomo team is working on it.

Greetings,
Michael

**Comment by HerbstO** [comment] 2022-04-12 04:18
Hello,

in the meantime is it possible to get the corresponding zip file via mail or download on Github?

Viele Grüße und „Bleiben Sie Gesund“
Ortwin Herbst
BAS3

Von: MichaelRoosz ***@***.***>
Gesendet: Montag, 11. April 2022 14:11
An: MichaelRoosz/plugin-GroupPermissions ***@***.***>
Cc: Herbst Ortwin ***@***.***>; Mention ***@***.***>
Betreff: Re: [MichaelRoosz/plugin-GroupPermissions] Compatibility with Matomo 4.5 (Issue #4)


Hello @HerbstO<https://github.com/HerbstO>,
thank you for your feedback.
The issue should be fixed in v4.0.2.
At the moment I cannot push released to the Matomo marketplace, but the Matomo team is working on it.

Greetings,
Michael

**Comment by MichaelRoosz** [comment] 2022-04-12 07:45
Hello @HerbstO ,

the new version 4.0.2 is now available in the Matomo Marketplace: https://plugins.matomo.org/GroupPermissions

Greetings,
MIchael

**Comment by HerbstO** [comment] 2022-04-12 07:47
Cool, Thanks, we will download the File.

Viele Grüße und „Bleiben Sie Gesund“
Ortwin Herbst
BAS3

Von: MichaelRoosz ***@***.***>
Gesendet: Dienstag, 12. April 2022 09:46
An: MichaelRoosz/plugin-GroupPermissions ***@***.***>
Cc: Herbst Ortwin ***@***.***>; Mention ***@***.***>
Betreff: Re: [MichaelRoosz/plugin-GroupPermissions] Compatibility with Matomo 4.5 (Issue #4)


Hello @HerbstO<https://github.com/HerbstO> ,

the new version 4.0.2 is now available in the Matomo Marketplace: https://plugins.matomo.org/GroupPermissions

Greetings,
MIchael

**Comment by MichaelRoosz** [comment] 2022-04-20 21:53
Hello @HerbstO,

version 4.0.4 is now available in the Matomo Marketplace: https://plugins.matomo.org/GroupPermissions,
It fixes a bug introduced in 4,0,1 - the site selection did not work.

Greetings,
MIchael

**Comment by HerbstO** [comment] 2022-04-21 05:08
Hello Michael,

Thanks for the new version, this one is awesome.
Especially the new user selection feature is fantastic and saves us a lot of clicks.

Thanks again for your good work

regards

Viele Grüße und „Bleiben Sie Gesund“
Ortwin Herbst
BAS3

Von: MichaelRoosz ***@***.***>
Gesendet: Mittwoch, 20. April 2022 23:53
An: MichaelRoosz/plugin-GroupPermissions ***@***.***>
Cc: Herbst Ortwin ***@***.***>; Mention ***@***.***>
Betreff: Re: [MichaelRoosz/plugin-GroupPermissions] Compatibility with Matomo 4.5 (Issue #4)


Hello @HerbstO<https://github.com/HerbstO>,

version 4.0.4 is now available in the Matomo Marketplace: https://plugins.matomo.org/GroupPermissions,
It fixes a bug introduced in 4,0,1 - the site selection did not work.

Greetings,
MIchael

**Comment by MichaelRoosz** [comment] 2022-04-21 10:22
Hello Ortwin,

thank you, happy to hear :) 

Greetings,
Michael

**Closed as completed by MichaelRoosz** 2022-04-21 10:22 UTC
